- README.md
Readme の更新
NA
他のリポジトリなどの作成も一段落したので，readmeを更新した
> Readme の更新

- .github/workflows/build_as_cxx.yml
- .github/workflows/check_coding_rule.yml
- Script/CI/check_coding_rule.json
- Script/CI/check_coding_rule.py
最低限のコード規約をチェックするお手製CIを追加
- https://github.com/ut-issl/c2a-core/issues/3
- えいやで作った規約チェックスクリプトを追加
- いくつか未だに直しきれていない規約違反があるため，有効化できていないルールもある
- 今後 https://github.com/ut-issl/c2a-core/issues/41 をしていきたい
CIが通ればOK
> 最低限のコード規約をチェックするお手製CIを追加

- .github/workflows/build_as_cxx.yml
- Examples/minimum_user_for_s2e/src/s2e_mockup/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/s2e_mockup/CMakeSettings.json
- Examples/minimum_user_for_s2e/src/s2e_mockup/main.cpp
S2Eとリンクできるか確認するためのモックアップ
- #35 (Issueではないが)
C2A単体でビルドが通っていてもS2Eとリンクできないとつらい
CIのWindows runnerでこれをビルドして通ればよし
N/A
何かあれば
- 関連する Projects が存在する場合，それの紐付けを行うこと
- Assignees を設定すること
- 可能ならば Reviewers を設定すること
- 可能ならば `priority` ラベルを付けること
> S2E mockup

- .github/labels.yml
S2E，WINGS関連のissue, PRを後でまとめて引っ掛けられるように
> Add WINGS, S2E label

- Drivers/Super/driver_super.c
- Drivers/Super/driver_super.h
- Examples/minimum_user_for_s2e/src/src_user/CmdTlm/block_command_user_settings.c
- Examples/minimum_user_for_s2e/src/src_user/CmdTlm/user_packet_handler.c
- System/ApplicationManager/app_manager.h
- System/EventManager/event_handler.h
- System/EventManager/event_logger.h
- System/TaskManager/task_dispatcher.c
WextraのWarningを消す
- https://github.com/ut-issl/c2a-core/issues/27
さっと直せるものを直した．残りはまた今度．
CIが通ればOK
ないはず
> WextraのWarningを消す

- Docs/General/Overview.md
> Docs内部のリンクを修正

- System/EventManager/event_logger.c
ELの軽微な性能改善
- https://github.com/ut-issl/c2a-core/issues/48
forを減らしたり，早く関数を返すようにしたり．
既存のELのpytestが通ることを確認．
なし．
> ELの軽微な性能改善

- .github/workflows/build_as_c89.yml
- Applications/CMakeLists.txt
- CMakeLists.txt
- Examples/minimum_user_for_s2e/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/src_user/Applications/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/src_user/CmdTlm/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/src_user/Drivers/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/src_user/IfWrapper/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/src_user/Library/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/src_user/Library/print.c
- Examples/minimum_user_for_s2e/src/src_user/Settings/CMakeLists.txt
- Library/CMakeLists.txt
- common.cmake
- #83
にて発生した`Printf()`2つあるのにリンクエラーが出てないことが発覚し，色々確認してみたところ色々直す必要がありそう
- #83
> リンク関係のCMakeの修正

- .github/workflows/build_as_c89.yml
- .github/workflows/build_as_cxx.yml
- .github/workflows/check_coding_rule.yml
- .github/workflows/check_encoding.yml
> 諸々のCIをdevelop,mainへのpushでも走らせる

- .github/workflows/build_as_c89.yml
あるPRでdiffが見えない問題の原因が，特定ソースコードとこのreview dogっぽいので，review dogを止める
- https://github.com/ut-issl/c2a-core/pull/119
> Disable reviewdog clang-tidy (github-check)

- Examples/minimum_user_for_s2e/src/s2e_mockup/CMakeLists.txt
- Examples/minimum_user_for_s2e/src/s2e_mockup/main.cpp
S2Eの方のC2A initの修正に追従
- Fix #69 
- https://gitlab.com/ut_issl/s2e/s2e_core_oss/-/merge_requests/168
詳しく
CIが通ればよし
> S2E mockupの更新

- System/EventManager/event_handler.c
EHのコマンドパラメタ取得方法の更新
- 関連: https://github.com/ut-issl/c2a-core/issues/50
コマンドパラメタ取得方法の改修が https://github.com/ut-issl/c2a-core/issues/46 で改良されたので，EHをそれに準拠させる
https://github.com/ut-issl/c2a-core/blob/8ff38212991e8b26b497f9d33880e74310b8eb6f/Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
> EHのコマンドパラメタ取得方法の更新

- Applications/nop.c
- Applications/nop.h
NOPにdoxygenコメントを追加
- https://github.com/ut-issl/c2a-core/issues/145
CIが通ればOK
> NOPにdoxygenコメントを追加

- Applications/anomaly_handler.c
- Applications/divided_cmd_utility.c
- Applications/event_utility.c
- Applications/gs_command_dispatcher.c
- Applications/memory_dump.c
- Applications/nop.c
- Applications/realtime_command_dispatcher.c
- Applications/telemetry_manager.c
- Applications/timeline_command_dispatcher.c
- Applications/utility_command.c
- Applications/utility_counter.c
- Docs/General/CodingRule.md
- Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_gs.c
- Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.c
- Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
- System/ApplicationManager/app_info.c
- System/ApplicationManager/app_info.h
- System/TaskManager/task_dispatcher.c
- AppInfoにdoxygenコメントを追加
- コード規約に合わせるように修正
- https://github.com/ut-issl/c2a-core/issues/145
CIが通ればOK
> AppInfoにdoxygenコメントを追加，コード規約に合わせるように修正

- Applications/gs_command_dispatcher.c
- Applications/gs_command_dispatcher.h
GSCDにdoxygenコメントを追加
- https://github.com/ut-issl/c2a-core/issues/145
CIが通ればOK
> GSCDにdoxygenコメントを追加

- .github/workflows/build_as_c89.yml
Reverts ut-issl/c2a-core#120
SJIS破壊記念Revert(この問題はSJISにより発生していたので)
> Revert "Disable reviewdog clang-tidy (github-check)"

- Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
GS ドライバーのinit に CCSDS config の初期化を追加
無し
GS ドライバーのinit に CCSDS config の初期化を追加した
テストが通れば
無し
> GS ドライバーのinit に CCSDS config の初期化を追加

- Docs/General/release.md
- Docs/README.md
- README.md
- c2a_core_main.h
リリースとバージョニングについての整備
- https://github.com/ut-issl/c2a-core/issues/141
- https://github.com/ut-issl/c2a-core/issues/169
- https://github.com/ut-issl/c2a-core/issues/170
diffを参照
> リリースとバージョニングについての整備

- Docs/Core/communication.md
パケットの記述をドキュメントに追加
- https://github.com/ut-issl/c2a-core/issues/135
> パケットの記述をドキュメントに追加

- TlmCmd/packet_handler.c
- TlmCmd/packet_handler.h
- TlmCmd/packet_list.c
- TlmCmd/packet_list.h
CTCP分離とSpacePacket実装に伴う，PHの微修正とPLのコメント修正
- https://github.com/ut-issl/c2a-core/issues/225
コメント追加と，アサーションの強化
テストがすべて通ればOK
> CTCP分離とSpacePacket実装に伴う，PHの微修正とPLのコメント修正

- Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.h
- Examples/minimum_user_for_s2e/src/src_user/Drivers/Etc/UART_TEST.h
- Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils_sci_if.hpp
- Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/uart_sils_sci_if.hpp
- Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/TaskLists/InitialTL.h
- Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/InitialSL.h
- Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/NopSL.h
- Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/SequenceItems.h
- Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/mode_definitions.h
- Examples/minimum_user_for_s2e/src/src_user/Settings/System/AppManagerParams.h
- Examples/minimum_user_for_s2e/src/src_user/Settings/initial_settings.h
- Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCFrame.h
- Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCSegment.h
- Library/ascii_conv.h
- Library/endian_conv.h
- Library/majority_vote_for3.h
- Library/print.h
- Script/CI/check_coding_rule.json
- Script/CI/check_coding_rule.py
インクルードガードのチェックを有効に
- https://github.com/ut-issl/c2a-core/issues/231
CIが通ればOK
> インクルードガードのチェックを有効に

- Drivers/Super/driver_super.c
- Drivers/Super/driver_super.h
Driver Super の doxygen コメントの修正
NA
関数定義部分から関数宣言部分へ移動
CIが通ればOK
> Driver Super の doxygen コメントの修正

- c2a_core_main.h
Update version (v3.5.0)
NA
v3.5.0 リリース前の，バージョン上げ
すべてのテストを再度通した
> Update version (v3.5.0)

- c2a_core_main.h
Revert "Update version (v3.5.0)"
NA
- This reverts commit 283ce2eaf9f6886fb750d51a8180358b8c1bc76e.
- https://github.com/ut-issl/c2a-core/pull/243#discussion_r800330969 で CI 上の問題が生じているため， main update ができなくなり，一旦バージョンを戻す
NA
- この後，問題を直し， https://github.com/ut-issl/c2a-core/pull/243 をやり直す．
> Revert "Update version (v3.5.0)"

- c2a_core_main.h
Update version (v3.5.0): やり直し
- https://github.com/ut-issl/c2a-core/pull/241
- https://github.com/ut-issl/c2a-core/pull/244
- https://github.com/ut-issl/c2a-core/pull/245
- https://github.com/ut-issl/c2a-core/pull/243
CIがよろしくなく，main updateでCIが通らなかったことの対応が終わったので，バージョンを上げ直す
CIと既存のテストが全て通ればOK
> Update version (v3.5.0): やり直し

- Examples/minimum_user_for_s2e/README.md
- README.md
> SILSなどの記載をreadmeに追加

- .github/workflows/build_with_s2e.yml
S2Eと一緒にビルドするCIを入れる
- https://github.com/ut-issl/c2a-core/issues/256
- https://github.com/ut-issl/s2e-user-for-c2a-core/pull/9 からの流用
- S2E Coreはバージョンを固定してます
> S2Eと一緒にビルドするCIを入れる

- System/EventManager/event_logger.h
- TlmCmd/command_dispatcher.c
- TlmCmd/command_dispatcher.h
- TlmCmd/packet_list.c
- TlmCmd/packet_list.h
CDIS などの修正
- https://github.com/ut-issl/c2a-core/issues/214
- コメント等の整備
- 命名規則の修正
- NULLチェックの追加
- その他修正
テストが全て通ればOK
特になし
> CDIS などの修正

- README.md
Readmeの注釈をGFMの新機能にする
NA
- https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/
> Readmeの注釈をGFMの新機能にする

- .github/workflows/build_as_c89.yml
CIが通らない問題を解決
NA
https://github.com/ut-issl/c2a-core/runs/5422728649?check_suite_focus=true みたいな落ちが頻繁に起きていた．
> CIが通らない問題を解決

- Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
GS の受信時刻の修正
N/A
GS の受信時刻をフレーム確定後ではなく、TC Frame であることが確定してから、にした
手元で pytset を通した
小
> GS の受信時刻の修正

- Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
ELデバッグ出力を短く
NA
ちょっと長いので（バランスが悪いので）
> ELデバッグ出力を短く

- Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
UTL_cmdのpytestの修正
CYCLES_PER_SECの補正項が一部反映されていない箇所があり，CIのpytestがしばしば落ちていたので，修正。
> UTL_cmdのpytestの修正

- Script/CI/check_coding_rule.py
- Script/CI/check_encoding.py
Pythonスクリプトの返り値を整理
- https://github.com/ut-issl/c2a-core/issues/237
CIでテストした
> Pythonスクリプトの返り値を整理

- Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_aobc.c
- Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_aobc.h
- Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.c
- Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.h
- Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.c
- Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.h
- Examples/minimum_user_for_s2e/src/src_user/Drivers/Etc/UART_TEST.c
- Examples/minimum_user_for_s2e/src/src_user/Drivers/Etc/UART_TEST.h
- Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils.cpp
> コメントスタイルの微修正

- Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/Applications/test_timeline_command_dispatcher.py
- c2a_core_main.h
TLCDのpytestを追加
- https://github.com/ut-issl/c2a-core/issues/164
詳しく
作ったpytestが通った
toolsは以下の修正が必要
- https://github.com/ut-issl/python-wings-interface/pull/17
これの後にマージする
- https://github.com/ut-issl/c2a-core/pull/314
> Pre Release (v3.6.0-beta.3): TLCDのpytestを追加

- .github/workflows/build_as_c89.yml
- .github/workflows/build_as_cxx.yml
- .github/workflows/build_with_s2e.yml
- CMakeLists.txt
libC2Aのリンクの修正
- https://github.com/ut-issl/s2e-user-for-c2a-core/issues/19
> Fix libC2A build

- Examples/minimum_user_for_s2e/src/src_user/TlmCmd/common_tlm_packet.c
- TlmCmd/Ccsds/tlm_space_packet.c
- TlmCmd/Ccsds/tlm_space_packet.h
- TlmCmd/telemetry_generator.c
> TSP周りのflagsの綴りを修正

- Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/sample.ops
> コマンドファイルのサンプルを追加

- Script/CI/check_coding_rule.py
コーディング規約チェックスクリプトで，エラーがでないものがあったことの修正
> コーディング規約チェックスクリプトで，エラーがでないものがあったことの修正

- Applications/divided_cmd_utility.h
- Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sequence_items.c
- Script/CI/check_coding_rule.py
- TlmCmd/common_cmd_packet_util.c
- TlmCmd/common_cmd_packet_util.h
CCP Util に param generator を追加
NA
CCP の param をかんたんに準備できる generator を追加実装
検証できぬ．．．．
既存のコードを置き換えて，全てのテストを通し直すことでOKとする？
> CCP Util に param generator を追加

- c2a_core_main.h
Update version (v3.6.0)
NA
v3.6.0 リリース前の，バージョン上げ
すべてのテストを再度通した
> Update version (v3.6.0)

- README.md
> README のリンク修正

- Drivers/Protocol/eb90_frame_for_driver_super.c
- Examples/minimum_user/src/src_user/TlmCmd/Ccsds/tc_transfer_frame.c
- Library/crc.c
- Library/crc.h
CRCライブラリの軽微な修正
- https://github.com/ut-issl/c2a-core/issues/392
主に規約
また，CCITT right は使わない割にメモリを食っているのでコメントアウト
CIが通ればOK
> CRCライブラリの軽微な修正

- Docs/Core/communication.md
- Docs/Driver/communication_with_components.md
- Docs/Driver/overview.md
- Docs/README.md
- Examples/2nd_obc_user/README.md
コンポ間通信や frame についてのドキュメントを追加
- https://github.com/ut-issl/c2a-core/issues/394
- https://github.com/ut-issl/c2a-core/issues/53
- https://github.com/ut-issl/c2a-core/issues/56
> コンポ間通信や frame についてのドキュメントを追加

- Docs/General/release.md
> リリースドキュメントに微修正

- c2a_core_main.h
Update version (v3.7.0)
NA
v3.7.0 リリース前の，バージョン上げ
> Update version (v3.7.0)

- Examples/minimum_user/src/src_user/TlmCmd/Ccsds/vcdu.c
vcdu replay flag を追加
N/A
DR 再生で vcdu replay flag が追加されていなかったので追加した
手元で pytest を通した
> vcdu replay flag を追加

- Examples/minimum_user/src/src_user/Drivers/Com/gs.c
GS Driver の enum の命名を修正
NA
see dfiff
> GS Driver の enum の命名を修正

- Library/crc.c
- Library/crc.h
> CCITT Right の CRC を有効化

- Examples/minimum_user/src/src_user/Settings/Modes/TaskLists/tl_initial.c
Task List での GS 受信, 実行の頻度を増加
N/A
Task List で GS CMD PH, GS CMD DISPATCHER の頻度が rotate で少なくなっていたのでそれを 1 Hz に上げた
手元で検証が通った
> Task List での GS 受信, 実行の頻度を増加

- Examples/2nd_obc_user/CMakeLists.txt
- Examples/minimum_user/CMakeLists.txt
cmakelists の USE_SCI_COM_WINGS の修正
CI が通ればOK
> cmakelists の USE_SCI_COM_WINGS の修正

- Drivers/Super/driver_super.c
- Drivers/Super/driver_super.h
DS のコメントスタイルを修正
NA
この後 DS 関連 PR をたくさんだすので，その前にコメントスタイルを更新
CI が通ればOK
- https://github.com/ut-issl/c2a-core/pull/501 を先にマージする
> DS のコメントスタイルを修正

- Drivers/Super/driver_super.c
- Drivers/Super/driver_super.h
DS の関数の順序を微修正
NA
getter → setter の順に統一
既存のテストがすべて通った
- https://github.com/ut-issl/c2a-core/pull/506 を先にマージする
> DS の関数の順序を微修正

- c2a_core_main.h
Update version (v3.8.0)
- https://github.com/ut-issl/c2a-core/issues/468
v3.7.0 リリース前の，バージョン上げ
> Update version (v3.8.0)

- TlmCmd/packet_handler.h
PH_ACK のコメントを微修正
N/A
diff を参照
CI 通れば OK
> PH_ACK のコメントを微修正

- Examples/2nd_obc_user/src/src_user/Settings/Modes/TaskLists/tl_initial.c
BC_AR_GS_RELATED_PROCESS を combine にして，Cmd受付処理の頻度をあげる (2nd OBC)
NA
- https://github.com/ut-issl/c2a-core/pull/451 を MOBC だけでなく 2nd OBC にもあてる
CI が通ればOK
> BC_AR_GS_RELATED_PROCESS を combine にして，Cmd受付処理の頻度をあげる (2nd OBC)

- System/EventManager/event_logger.h
EL の doxygen コメントの軽微な修正
（）追加しただけ
> EL の doxygen コメントの軽微な修正

- TlmCmd/common_cmd_packet_util.c
- TlmCmd/common_cmd_packet_util.h
CCP_form_and_exec_rtc_to_other_obc を追加する
N/A
他OBCへの RT cmd 即時実行用の補助関数を追加する
TBA
> CCP_form_and_exec_rtc_to_other_obc を追加する

- build.rs
`clippy --fix` をかけた
- https://github.com/ut-issl/c2a-core/pull/603#issuecomment-1572549471
- Rust の部分だけ（これについても，挙動は変わらない）
> Fix build.rs by clippy

- Applications/telemetry_manager.h
- Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
> コマンドの注釈を微修正

- Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
EH の pytest が特定環境で通らないことの修正
NA
テスト時間短縮のために攻めすぎてた
CIとテストが通ればOK
> EH の pytest が特定環境で通らないことの修正

- Cargo.toml
- c2a_core_main.h
Update version (v3.9.1)
NA
v3.9.1 リリース前の，バージョン上げ
> Update version (v3.9.1)

- Cargo.toml
- c2a_core_main.h
Update version (v3.9.2)
NA
v3.9.2 リリース前の，バージョン上げ
> Update version (v3.9.2)

- Cargo.toml
- c2a_core_main.h
Update version (v3.10.0)
NA
v3.10.0 リリース前の，バージョン上げ
> Update version (v3.10.0)

- Applications/timeline_command_dispatcher.c
PL_BC_LIST_CLEARED を level high で EL 登録する
- https://github.com/ut-issl/c2a-core/issues/639
issue の通り
CIがとおればOK
> PL_BC_LIST_CLEARED を level high で EL 登録する

- Applications/timeline_command_dispatcher.c
- Cargo.toml
- README.md
- c2a_core_main.h
以下の微修正
- https://github.com/ut-issl/c2a-core/pull/633
今回のupdate 分
- https://github.com/ut-issl/c2a-core/pull/640
- https://github.com/ut-issl/c2a-core/pull/641
https://github.com/ut-issl/c2a-core/tree/e4bd719464da7e3b2a0e6427fe9aa2ad2e973367/Examples/minimum_user/src/src_user/Test を全て通した
> Update main (v3.10.1) on 2023-09-26
