Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
GS で Warningが出ていたので修正
N/A
if 文で = を使って変数代入してたら Warning出たので処理分けた
ISSL側のOBCで検証済み
小
=> GS で Warningが出ていたので修正

Examples/minimum_user_for_s2e/src/src_user/c2a_main.c, System/ApplicationManager/app_manager.c, System/TimeManager/obc_time.c, System/TimeManager/obc_time.h, System/TimeManager/time_manager.c, System/TimeManager/time_manager.h, c2a_core_main.c
初期化中の get clock の動作変更
* https://github.com/ut-issl/c2a-core/issues/47
TMGR の初期化に Initializing flag を設けて get_master_clock の動作を変えた。また get_clock_from_boot を新設
SILS動作を確認した
大 (初期化にかかわるので)
=> 初期化中の get clock の動作変更

Examples/minimum_user_for_s2e/CMakeLists.txt, Library/CMakeLists.txt
S2EでPrintfが出力されない問題を修正
NA
- `SHOW_DEBUG_PRINT_ON_SILS` の設定場所を `add_subdirectory` のCMakeLists読み込み前にしないと効かない？
- `Printf` はuser側のものをつかうので，coreをビルド対象から外す
- https://github.com/ut-issl/c2a-core/blob/cac210693b2b3bbcdca8f2cd5ec0002b5ad6eadf/Library/print.c#L7-L8
手元でS2Eを回し，Printfが正しく出力されることを確認
`Printf` が２つ存在していたことになるのに，なんで今までリンク時にエラーが出なかったのか？適当にリンクされる？
=> Fix CMakeLists.txt for Printf

CmdTlm/packet_list.c, Drivers/Super/driver_super.c
ISSL MOBCのマイコンIDEでのWarningを消す
- https://github.com/ut-issl/c2a-core/issues/80
issue参照
ISSL MOBC環境でWarningが出ないことを確認．
=> ISSL MOBCのマイコンIDEでのWarningを消す

.github/workflows/check_coding_rule.yml, Script/CI/check_coding_rule.json, Script/CI/check_coding_rule.py
CIが正しく動いてなさそう？
手元で回すと落ちるものが，CIでは通ってる気がする？
シンボリックリンク内でのpythonが正しくパスを参照しない
TBW
CIが正しく落ちて，正しく通ればOK
=> Fix check_coding_rule CI

Examples/minimum_user_for_s2e/src/src_user/c2a_main.c
WDT_init を C2A_init_ に追加
- https://github.com/ut-issl/c2a-core/issues/96
WDT_init が無かったので C2A_init_ に追加した. user 定義なので user 側に追加した
SILS が動くのを確認した
小
=> WDT_init を C2A_init_ に追加

.github/workflows/build_as_c89.yml, .github/workflows/build_as_cxx.yml, Examples/minimum_user_for_s2e/CMakeLists.txt, Examples/minimum_user_for_s2e/src/src_user/c2a_main.c, common.cmake
`-Wpendatic`を付けないと真に規格に準拠したワーニングは出ないので，追加する
- #94 
- 1行コメント(`// hoge~`)がC99だった(が，HEWは独自拡張でサポートされている)
- clangでは`-Wno-comment`で↑のwarningを握り潰せる
- gccではできない(`-Wcomment`は別の意味)ので，`gcc -Werror`ができない
- `gcc -Werror`だけスキップして`-Werror`はclangでやる
- clangはShift JIS無理
- clangでビルドする前にnkfでShift JIS->UTF-8
- C89に準拠させるのは別にやる
CIが`-Werror`のやつは適切に落ちるようになり，それ以外は通ればよし
=> C89規格に準拠したワーニングを出す

CmdTlm/telemetry_frame.c, Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
C89のWallででるWarningをすべて消す
- https://github.com/ut-issl/c2a-core/issues/94
NA
WerrorのCIが通るようになればOK
- GSのバグも直しているので，このCoreをuser側で取り込む場合はそこも反映させること！
=> C89のWallででるWarningをすべて消す

CmdTlm/block_command_table.c
Cmd_BCT_OVERWRITE_CMD を可変長 Cmd に対応
- https://github.com/ut-issl/c2a-core/issues/71
Cmd_BCT_OVERWRITE_CMD を可変長 Cmd に対応するようにした
テストに全部通った & SILS でテストした結果BCTが書き換わった
小
=> Cmd_BCT_OVERWRITE_CMD を可変長 Cmd に対応

.github/workflows/build_as_c89.yml
`clang -Wextra`の設定でclang-tidyにワーニングを出させ，それをreviewdogで表示する
- #45 
詳しく
XX系の動作がガラッと変わる，とか．
何かあれば
- 関連する Projects が存在する場合，それの紐付けを行うこと
- Assignees を設定すること
- 可能ならば Reviewers を設定すること
- 可能ならば `priority` ラベルを付けること
=> clang-tidyでreviewdogにビルドCIのerror,warningを出させる

CmdTlm/command_analyze.c, CmdTlm/common_tlm_cmd_packet_util.c
某IDE で出ていたWarning を削除する
- https://github.com/ut-issl/c2a-core/issues/97
- https://github.com/ut-issl/c2a-core/issues/80
`CmdTlm/common_tlm_cmd_packet_util.c` と `CmdTlm/command_analyze.c` で出ていた Warning を削除した
build出来ることを確認した
小
=> Warning 消し

System/TimeManager/obc_time.c, System/TimeManager/obc_time.h, System/TimeManager/time_manager.c, System/TimeManager/time_manager.h
ObcTimeとTMGRで関数の順番を変更した。
- https://github.com/ut-issl/c2a-core/issues/124
- ObcTime関連の関数→unixtime関連の関数→コマンド関数の順に並び替えた
- getter→変換系の関数→演算系の関数 の順にした
- 変換系の関数は msec→sec の順に統一した
diffが見にくくなりそうなので、関数の順番を整理するPRを分けて先にマージしたい。
以下が通った。
https://github.com/ut-issl/c2a-core/blob/5a796cada870a51762555e5edb701a6dcdb1b9e8/Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
=> ObcTimeとTMGRで関数の順番を変更

Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py, System/EventManager/event_handler.c
EHでの二分探索をbsearchで書き直した
- https://github.com/ut-issl/c2a-core/issues/50
他にも，issueにある `範囲外アクセスの可能性ありそう` も直した．
https://github.com/ut-issl/c2a-core/tree/fb90df7b9c178911c794611923e52a1d93d86f21/Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager
なし
EHの改修が進んでいったら，1 eventで複数EH発火などもテストに入れたほうが良さそう
=> EHでの二分探索をbsearchで書き直した

CmdTlm/telemetry_frame.c
TFの変数の型を修正し，Wextraを消す
- https://github.com/ut-issl/c2a-core/issues/27
適当にSILSを動かして問題なかった
=> TFの変数の型を修正し，Wextraを消す

Examples/minimum_user_for_s2e/src/src_user/Test/README.md, Examples/minimum_user_for_s2e/src/src_user/Test/utils/wings_utils.py
ひとことで
- https://github.com/ut-issl/c2a-core/issues/44
認証情報を環境変数から取得できるようにして、取得できた場合は `authorization.json`
手元で test が動くことを確認した
何かあれば
=> 認証情報を環境変数から取得できるようにした

CMakeLists.txt, common.cmake
32bit専用のGCCなどは`-m32`が無いことがあるので，コンパイラが32bitであることが分かる場合は明示的にそれを指定した上で`-m32`などをコンパイルオプションに追加しないようにする
NA
別環境で確認
=> -m32が無いコンパイラのためのCMakeの修正

README.md
README に discussion のリンクを貼った
- https://github.com/ut-issl/c2a-core/discussions
- https://github.com/ut-issl/c2a-core/issues/173
=> Add link to discussion in readme

Examples/minimum_user_for_s2e/src/src_user/Script/AddSection/AddSection.pl, Examples/minimum_user_for_s2e/src/src_user/Script/AddSection/settings.pl, Script/AddSection/AddSection.pl, Script/AddSection/settings.pl
文字コードがUTF-8になったことによる， `#pragma section` スクリプトの修正
- https://github.com/ut-issl/c2a-core/issues/21
- https://github.com/ut-issl/c2a-core/pull/185 に漏れがあったので，追加
無事にスクリプトが動くことを確認
=> 文字コードがUTF-8になったことによる， `#pragma section` スクリプトの修正

IfWrapper/uart.h
Linuxなど用に、UARTをデバイスファイル名として設定できるようにした
NA
Linux環境で確認済み
=> UART_Configにファイルシステム向けの設定を追加

Docs/General/release.md, c2a_core_main.h
Pre Release (v3.5.0-beta.0): UTF-8 への変更に伴い，Tools に非互換アップデートが入ったことによる Pre Release
- https://github.com/ut-issl/c2a-core/pull/185
- https://github.com/ut-issl/c2a-tlm-cmd-code-generator/pull/9
- https://github.com/ut-issl/c2a-enum-loader/pull/8
この後，Pre-release を発行し，Tools類もReleaseを打つ．
NA
=> Pre Release (v3.5.0-beta.0): UTF-8 への変更に伴い，Tools に非互換アップデートが入ったことによる Pre Release

Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py, System/TimeManager/time_manager.c, System/TimeManager/time_manager.h, c2a_core_main.h
UTL_cmd のpytestを追加した
- https://github.com/ut-issl/c2a-core/issues/175
TMGR のテストに UTL_cmd が正しく打てるかどうかの確認を追加した。
作成したpytestが通った
小
python-wings-if側のPRの検証にもなっている
- https://github.com/ut-issl/python-wings-interface/pull/6
=> Pre Release (v3.5.0-beta.1): UTL cmd のテストを追加する

.flake8, .github/workflows/python_check_format.yml, .github/workflows/python_lint.yml, Examples/minimum_user_for_s2e/src/src_user/Test/README.md, Examples/minimum_user_for_s2e/src/src_user/Test/test/conftest.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/CmdTlm/test_command_analyze.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/AnomalyLogger/test_anomaly_logger.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/ModeManager/test_mode_manager.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TaskManager/test_task_dispatcher.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_obc_time.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/WatchdogTimer/test_watchdog_timer.py, Examples/minimum_user_for_s2e/src/src_user/Test/utils/c2a_enum_utils.py, Examples/minimum_user_for_s2e/src/src_user/Test/utils/wings_utils.py, Script/CI/check_coding_rule.py, Script/CI/check_encoding.py, pyproject.toml
pythonのフォーマットチェックCIとリンタCIをいれる
- https://github.com/ut-issl/c2a-core/issues/89
- 以下を入れた
- formatter: https://github.com/reviewdog/action-black
- linter: https://github.com/reviewdog/action-flake8
- １行最大文字数はとりあえず100
- flake8 で `ignore = E203,W503,W504` としてるのは，blackと競合するから
- flake8 で `ignore = E402` としているのは https://github.com/ut-issl/c2a-core/issues/195 で対応
- blackは  https://github.com/ut-issl/c2a-core/blob/9e2faa95eb20abf2975ceea2cb96b5beb9045e70/.github/workflows/python_check_format.yml#L22-L23 としてる
- flake8 は https://github.com/ut-issl/c2a-core/blob/9e2faa95eb20abf2975ceea2cb96b5beb9045e70/pyproject.toml#L6-L8 としている．
CIと既存のテストがすべて通ればOK
今後，このCIの通過が必須になる
=> pythonのフォーマットチェックCIとリンタCIをいれる

.github/workflows/build_as_c89.yml, .github/workflows/build_as_cxx.yml
ビルドCIを，すべてのPRで回すように設定
NA
https://github.com/ut-issl/c2a-core/pull/193#issuecomment-1014560773 で，発生．pathの管理がめんどくさいので，毎回回すようにする
NA
=> ビルドCIを，すべてのPRで回すように設定

CMakeLists.txt
ApplicationsとLibraryを使わない場合でも、add_subdirectoryによって
サブディレクトリ内のCMakeLists.txtが読み込まれていた
NA
別環境で確認
=> ApplicationsとLibraryを必要な場合のみadd_subdirectoryする修正

.flake8
flake8のignoreにE501をいれた
- https://github.com/ut-issl/c2a-core/issues/89
- https://github.com/ut-issl/c2a-tlm-cmd-code-generator/pull/14#issuecomment-1016605387 での議論でそうなったので，こちらにも反映
CIが通ればOK
=> Add E501 to ignore list for flake8

Script/CI/check_coding_rule.py
コード規約チェックCIのエラー出力を関数化する
- https://github.com/ut-issl/c2a-core/issues/22
- https://github.com/ut-issl/c2a-core/issues/22 もあるので，今書き下しているのをまとめて，エラー出力フォーマットを変更しやすいように & 画一的な出力になるようにする
適当に崩してみて，CIが正しく動くか確認する
=> コード規約チェックCIのエラー出力を関数化する

.github/workflows/check_coding_rule.yml
独自スクリプトによるコーディングスタイルチェックの結果をreviewdogを使って表示する
- https://github.com/ut-issl/c2a-core/issues/22
詳しく
XX系の動作がガラッと変わる，とか．
何かあれば
- 関連する Projects が存在する場合，それの紐付けを行うこと
- Assignees を設定すること
- 可能ならば Reviewers を設定すること
- 可能ならば `priority` ラベルを付けること
=> check_coding_ruleの出力をreviewdogから出す

.github/workflows/build_as_c89.yml, Script/CI/remove_duplicate_error.py
同一のファイルに対して同一のエラーが(異なるファイルから)出ている時にreviewdogの出力が重複するのを避ける
NA
- 例: https://github.com/ut-issl/c2a-core/runs/4952194939?check_suite_focus=true
=> Remove duplicate error on reviewdog

.github/workflows/check_coding_rule.yml, Script/CI/check_coding_rule.json
`check_coding_rule`のCIが落ちるべき時に落ちていなかったので修正
- https://github.com/ut-issl/c2a-core/pull/234 で発生
- https://github.com/ut-issl/c2a-core/pull/234#issuecomment-1028259117
=> Fix check_coding_rule workflow

README.md
C2A Coreの搭載実績を書く
- https://github.com/ut-issl/c2a-core/issues/168
ISTS発表論文から転記
=> C2A Coreの搭載実績を書く

Examples/minimum_user_for_s2e/src/src_user/Settings/Applications/data_recorder_define.h, Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/packet_handler_params.h, TlmCmd/packet_handler.c, TlmCmd/packet_handler.h
DRのないOBCで，不要なメモリを確保しないようにする
NA
stored tlmとreploay tlmのpacket listを，DRのないボードではメモリ確保しないようにした
- https://github.com/ut-issl/c2a-core/blob/a8eb378c663acea13099271cb9f94f8142687eee/Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/packet_handler_params.h#L35 をコメントインしてもビルドできることを確認（もちろん該当PLの参照は消した上で）
=> DRのないOBCで，不要なメモリを確保しないようにする

System/EventManager/event_handler.h
EHの設定のdefineの位置が不適切なのを直した
NA
user設定が反映されない位置にあったので，直した
CIが通ればOK
=> EHの設定のdefineの位置が不適切なのを直した

CMakeLists.txt, Examples/minimum_user_for_s2e/CMakeLists.txt
ALはdeprecatedなので，cmakelistsから外す
- https://github.com/ut-issl/c2a-core/issues/112
- Systemにあるのに，全然必須じゃないし，むしろ使わないほうが多いので
- 使いたいならuser側でビルドターゲットにいれる
=> ALはdeprecatedなので，cmakelistsから外す

Examples/minimum_user_for_s2e/src/src_user/Test/test/conftest.py
pytest confest で EL_CORE_GROUP_TLCD_DEPLOY_BLOCK EL が出るのを防ぐ
NA
TL2を消す前にBCを消していて，無効なBC展開が走り，ELが出ていた
=> pytest confest で EL_CORE_GROUP_TLCD_DEPLOY_BLOCK EL が出るのを防ぐ

Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py, Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py, System/EventManager/event_logger.h, TlmCmd/command_dispatcher.c
GSCD，TLCD，RTCDなどの実行時エラー履歴をELに記録して残す
- https://github.com/ut-issl/c2a-core/issues/129
実行時エラーがEL_TLOGテレメに登録されるのを SILSとwingsで確認した
小
=> GSCD，TLCD，RTCDなどの実行時エラー履歴を残す

Script/CI/check_coding_rule.json, Script/CI/check_coding_rule.py
コーディング規約チェックスクリプトに，ルール単位でのignoreを追加
- https://github.com/ut-issl/c2a-core/issues/308
- userでのcore update時に，規約も治すのがめんどくさいので，ルール単位で無効化できるようにした
=> コーディング規約チェックスクリプトに，ルール単位でのignoreを追加

Script/CI/check_coding_rule.py
コーディング規約スクリプトで，プリプロセッサの改行 `\` がエラーになる問題を修正
- https://github.com/ut-issl/c2a-core/issues/301
=> コーディング規約スクリプトで，プリプロセッサの改行 `\` がエラーになる問題を修正

Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py
test_command_dispatcher 内の sleep の時間を変更
N/A
これをやったところ，待機時間が足りずにテストが落ちたため修正した。
- https://github.com/ut-issl/python-wings-interface/pull/18
pytestが通った。
=> test_command_dispatcher 内の sleep の時間を変更

TlmCmd/common_cmd_packet_util.c, TlmCmd/common_cmd_packet_util.h
CCP register cmd 関数の追加
- https://github.com/ut-issl/c2a-core/issues/313
form と `PH_analyze_packet` をまとめた register を作成した
N/A
小
=> CCP register cmd 関数の追加

.github/workflows/build_with_s2e.yml, common.cmake
s2e-core更新に伴うCmake関連ファイルの修正
issueではないが、
https://github.com/ut-issl/s2e-user-for-c2a-core/pull/18
- s2e-coreでwarningを消すためにVSの`/MT`オプションが必要になったので、c2a-core内のcmakeについてもそのオプションを追加
- (これから実装するが、)Linux用にWINGSと接続する部分を消す修正も行う
手元でビルドできることを確認した
S2E/VS環境の人のみ
NA
NA
=> s2e-core更新に伴うCmake関連ファイルの修正

Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
telemetry_definition.c でAOBCの設定を消してしまっていたので、直す
N/A
このPRでテレコマgenerator の設定をミスっていた
- https://github.com/ut-issl/c2a-core/pull/314
CIが通ればOK
XX系の動作がガラッと変わる，とか．
何かあれば
=> telemetry_definition.c でAOBCの設定を消してしまっていたので、直す

Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py, System/TimeManager/time_manager.c, System/TimeManager/time_manager.h, c2a_core_main.h
WINGS側でUTLが0.1s精度で打てるようになったことへの対応
- https://github.com/ut-issl/c2a-core/issues/175
issueの残タスクである以下をやった
- 0.1sに対応
- 現実の時刻にテストを合わせる
- 過去時刻で通らないことの確認
手元でpytestが通った
- https://github.com/ut-issl/python-wings-interface/pull/22
と一緒にマージする。非互換なのでpre-releaseを打つ。
=> Pre Release (v3.6.0-beta.4): WINGS側でUTLが0.1s精度で打てるようになったことへの対応

Examples/minimum_user_for_s2e/CMakeLists.txt
CMakeで`option()`のデフォルト値として指定したいという意図のものが`set()`で設定されているので修正
- https://github.com/ut-issl/s2e-user-for-c2a-core/issues/19
=> Fix CMake option default value config

IfWrapper/spi.h
SPIヘッダをC89に対応
C2A coreのsampleでは使われてなかったので，CIに引っかかってなかった
=> SPIヘッダをC89に対応

Examples/minimum_user_for_s2e/CMakeLists.txt, Examples/minimum_user_for_s2e/src/src_user/c2a_main.c
Example userのmain関数をSILSの時には定義しないようにする
- 関連する issue
今のところこれで困っていることはあまりないが，libC2Aを他のものとリンクさせる時に`multiple definition`エラーが出ることがあるので，その修正
=> Ignore example user's main() on SILS environment

CMakeLists.txt, Examples/minimum_user_for_s2e/CMakeLists.txt, common.cmake
=> Fix/Add CMake build options for user

Docs/Core/communication.md
=> CCP_DEST_TYPE の説明を追記

Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_block_command_loader.py, Examples/minimum_user_for_s2e/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_test_bcl.c, TlmCmd/block_command_loader.c, TlmCmd/block_command_loader.h, TlmCmd/common_cmd_packet_util.c, TlmCmd/common_cmd_packet_util.h
CCP UTIL と BCL で sub OBC のコマンドに対応
N/A
sub OBC のコマンドをモード遷移のBC で打つ需要があったため実装した。APIDが異なるため現状のBCLでは sub OBC コマンドを登録できない。
- BCL の pytest が通った
- 手元で別のC2A_userのSILSを回して sub OBC にコマンドが配送されるところまで確認した
小
何かあれば
=> CCP UTIL と BCL で sub OBC のコマンドに対応

Examples/minimum_user/src/src_user/Settings/CMakeLists.txt, Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c, Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.h, Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h, Examples/minimum_user/src/src_user/Settings/TlmCmd/common_tlm_packet_define.h, TlmCmd/Ccsds/space_packet.c, TlmCmd/common_tlm_cmd_packet.h, TlmCmd/common_tlm_packet.h, TlmCmd/telemetry_generator.c
APIDのバリデーションをuser部に移動し， GENERATE_TLM で 2nd OBC の TI, Sequence counter を保存するようにした
- https://github.com/ut-issl/c2a-core/issues/350
- https://github.com/ut-issl/c2a-core/issues/155
tlm id が全OBCでユニークであること，という仮定はまだ外せてない（ので暫定）
既存のテストが全て通った
- APIDのバリデーションを各user で書く必要がある
- `CTP_APID_FROM_ME` を各userで定義する必要がある
- 各OBCのtlmで別のAPIDを割り振るようにする
- Sequence counterが，MOBCで統一ではなく，各APIDごとになる
- on board subnet timeはひとまずMOBCのTIを入れる（暫定処置）
=> APIDのバリデーションをuser部に移動し， GENERATE_TLM で 2nd OBC の TI, Sequence counter を保存するようにした

Applications/anomaly_handler.c, System/EventManager/event_handler.c, System/ModeManager/mode_manager.c, TlmCmd/common_cmd_packet.h, TlmCmd/common_cmd_packet_util.c, TlmCmd/common_cmd_packet_util.h
即時実行する CCP 作成関数の追加
- https://github.com/ut-issl/c2a-core/issues/323
- see diff
- 既存の部分を書き換えることで，既存のtestがすべて通ればOKということになる（にしてほしい．．．）
こういう部分ってどうtest書けば良いんだろうね？
=> 即時実行する CCP 作成関数の追加

Examples/minimum_user/src/src_user/TlmCmd/common_tlm_packet.c, TlmCmd/common_tlm_packet.h, TlmCmd/telemetry_generator.c
global time をユーザー定義できるようにした
N/A
global_time が今までゼロ埋めされていたが、ユーザー定義で好きな値を設定できるようにした
CIが通ればOK
=> global time をユーザー定義に

common.cmake
不要なCMake target propertyを消す
NA
- そもそもtarget propertyに`LANGUAGE`は存在しないので，無意味な指定
- ref: https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#target-properties
- Visual Studio 2019だとこれでコケてそう
CIが通ればよし
CMakeの修正なのでSILS環境下のみ．無意味な設定を削るだけなので動作は変わらないはず．
=> Remove unneeded CMake target_properties()

common.cmake
SSIA
- https://github.com/ut-issl/s2e-core/pull/155
`-rdynamic` はそもそもリンク時のオプションで， gcc はコンパイルだけの時(`-c`の時)でもこのオプション渡されても何食わぬ顔だけど，clang は偉いので `-c` の時はなんやねんこれというワーニングを吐いてる(リンクする時に渡される分にはOK)，ということだったっぽい．
_Originally posted by @sksat in https://github.com/ut-issl/s2e-core/issues/155#issuecomment-1172161683_
=> Fix set -rdynamic on link time only

Examples/minimum_user/src/src_user/TlmCmd/Ccsds/tc_transfer_frame.h
SCIDのデフォルト値を修正
WINGSのデフォルト値が変わったため
手元の最新WINGSで噛み合わせOK
=> SCIDのデフォルト値を修正

Examples/2nd_obc_user/sync_with_minimum_user.bat
Examples/2nd_obc_user と Examples/minimum_user の同期スクリプトの微修正
NA
- https://github.com/ut-issl/c2a-core/pull/386 での修正漏れ
- MOBC sample と AOBC (2nd OBC) sample でファイルが全く同じものを，暫定的にこのバッチファイルで同期しているが，上記PRで同一ではなくなったものを除外するのを忘れていた
=> Examples/2nd_obc_user と Examples/minimum_user の同期スクリプトの微修正

Drivers/Protocol/eb90_frame_for_driver_super.c, Drivers/Protocol/eb90_frame_for_driver_super.h
C2A標準CRCを CRC-16-IBM から CRC-16-CCITT に変える
- https://github.com/ut-issl/c2a-core/issues/390
See issue
minimum_user と 2nd_obc_user のテストが全て通った
=> C2A標準CRCを CRC-16-IBM から CRC-16-CCITT に変える

Drivers/Protocol/eb90_frame_for_driver_super.c, Drivers/Protocol/eb90_frame_for_driver_super.h, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.h, Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c, Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.h, c2a_core_main.h
Pre Release (v3.7.0-beta.2): C2A間通信の実装例に CRC のチェックを入れ，テストを通す
- https://github.com/ut-issl/c2a-core/issues/395
see issue
minimum_user と 2nd_obc_user のテストが全て通った
- https://github.com/ut-issl/c2a-core/pull/403 でCRCが変わってることに注意
- https://github.com/ut-issl/c2a-core/pull/403 とあわせて，コンポ間通信が非互換になるので pre release を打つ
=> Pre Release (v3.7.0-beta.2): C2A間通信の実装例に CRC のチェックを入れ，テストを通す

Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.c, Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.h, Drivers/Protocol/eb90_packet_for_driver_super.h, Drivers/Super/driver_super.c, Drivers/Super/driver_super.h, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.h, Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
C2A間通信など， CTCP on EB90 frame のコンポ間通信の Driver を書きやすくする Util を整備
- https://github.com/ut-issl/c2a-core/issues/400
see diff
minimum_user と 2nd_obc_user のテストが全て通った
=> C2A間通信など， CTCP on EB90 frame のコンポ間通信の Driver を書きやすくする Util を整備

Drivers/Super/driver_super.c, System/TimeManager/time_manager.c, TlmCmd/block_command_table.c
コマンド返り値が CCP_CmdRet に変わったことに付随する細かい改善
- https://github.com/ut-issl/c2a-core/issues/420
関連としては
- https://github.com/ut-issl/c2a-core/issues/376
- https://github.com/ut-issl/c2a-core/pull/417
せっかくエラーコードがあるものは，それも残すようにした．
既存のテストが全て通った
とくになし
=> コマンド返り値が CCP_CmdRet に変わったことに付随する細かい改善

Applications/anomaly_handler.c, Applications/timeline_command_dispatcher.h, Applications/timeline_command_dispatcher_id_define.h, Examples/2nd_obc_user/src/src_user/Settings/Modes/Transitions/sl_initial.c, Examples/2nd_obc_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c, Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sequence_items.h, Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sl_initial.c, Examples/minimum_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c, System/EventManager/event_handler.c, System/ModeManager/mode_manager.c, TlmCmd/block_command_loader.c, TlmCmd/block_command_loader.h, TlmCmd/common_cmd_packet_util.h, TlmCmd/packet_handler.h
循環参照を防ぐために TLCD_ID の定義を外部ファイル化
NA
CIが通ればOK
=> 循環参照を防ぐために TLCD_ID の定義を外部ファイル化

IfWrapper/spi.h
SPI_CS_STATE_AFTER_TXの値変更
NA
`SPI_CS_STATE_AFTER_TX_LOW`と`SPI_CS_STATE_AFTER_TX_HIGH`を入れ替え、
送信後Highにする動きがデフォルトであることを明確にする
CIがとおればOK
SPI通信を使っている箇所
SPI_init()にてSPI_Config.cs_state_after_txを明示的に初期化することを推奨
上記初期化を行っておらず、SPI_CS_STATE_AFTER_TXを使った分岐を実装しているuserだと
本改修を取り込むと初期化直後の挙動が変わる可能性がある
=> SPI_CS_STATE_AFTER_TXの値変更

Examples/2nd_obc_user/src/src_user/Applications/UserDefined/debug_apps.c, Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c, Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.c, Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.h, Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.c, Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.h, Examples/minimum_user/src/src_user/Applications/UserDefined/debug_apps.c, Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py, Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py, Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c, Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.c, Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.h, System/EventManager/event_handler.c, System/EventManager/event_logger.h, System/TaskManager/task_dispatcher.c, System/TaskManager/task_dispatcher.h, TlmCmd/block_command_executor.c, TlmCmd/command_analyze.c, TlmCmd/command_analyze.h, TlmCmd/command_dispatcher.c, TlmCmd/command_dispatcher.h, TlmCmd/common_cmd_packet.h, TlmCmd/common_cmd_packet_util.c, TlmCmd/common_cmd_packet_util.h, TlmCmd/packet_handler.c, TlmCmd/packet_handler.h
Cmd の返り値を CCP_EXEC_STS から CCP_CmdRet に（つづき）
- https://github.com/ut-issl/c2a-core/issues/376
- https://github.com/ut-issl/c2a-core/pull/417 の `別 PR でやる部分` 
- ここでは tlm db の修正までは行わない（コメントアウトしてる）
- したがってテストも通らない
- テストなどは https://github.com/ut-issl/c2a-core/pull/426 で行う
=> Cmd の返り値を CCP_EXEC_STS から CCP_CmdRet に（つづき）

Applications/timeline_command_dispatcher.c
fix include bug
- https://github.com/ut-issl/c2a-core/issues/435
二重 include で別 IDE で warning が出ていたので
CI が通ればOK
=> fix include bug

Applications/timeline_command_dispatcher.c, System/EventManager/event_handler.c
EH 対応時の BC 展開時の EL がうるさいことを直す（時間調整時は LOW にした）
- https://github.com/ut-issl/c2a-core/issues/389
- BC 展開が時間調整でワーニングになった場合は， エラーレベルを HIGH ではなく LOW にした
minimum uer の test が全て通った
=> EH 対応時の BC 展開時の EL がうるさいことを直す（時間調整時は LOW にした）

Examples/minimum_user/src/src_user/Drivers/Com/gs.c
- https://github.com/ut-issl/c2a-core/pull/446 のマージ先ブランチを間違えたので， develop にマージし直す．
=> GS Driver の enum の命名を修正 (やり直し)

Drivers/Super/driver_super.c, Drivers/Super/driver_super.h
DS のフレーム長取得にパケット内部のエンディアンを考慮
- https://github.com/ut-issl/c2a-core/issues/442
see diff
既存のテストが全て通った
本質的な検証はテストではできないのでしっかりレビューして欲しい
後方互換性あり
=> DS のフレーム長取得にパケット内部のエンディアンを考慮

Docs/Core/communication.md, Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h, Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h, TlmCmd/packet_handler.c
MOBC経由でのパケット配送時に，2nd OBC での Cmd 実行種別のバグを修正
- https://github.com/ut-issl/c2a-core/issues/458
Issue 参照
既存のテストが全て通った（2nd obc も）
=> MOBC経由でのパケット配送時に，2nd OBC での Cmd 実行種別のバグを修正

Drivers/Super/driver_super.c, Drivers/Super/driver_super.h, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c, Examples/2nd_obc_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h, Examples/2nd_obc_user/sync_with_minimum_user.bat, Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c, Examples/minimum_user/src/src_user/Drivers/Com/gs.c, Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c, Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h, Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_super_params.h
DriverSuper のバッファサイズを可変にする 
- https://github.com/ut-issl/c2a-core/issues/443
- DS のバッファサイズを可変にして，メモリ使用量をへらす．
- ここでは，全Driverで共通値だったフレームサイズの制限をなくすことが主眼
- その後のパフォーマンス改善や整理は https://github.com/ut-issl/c2a-core/issues/449 で
すべてのテストが通った
これからは，Driverが自身でbufferを準備し，DSに食わせないとだめ
- 深く関わるので，user側の core update は https://github.com/ut-issl/c2a-core/pull/453 と一緒にやると良い
=> DriverSuper のバッファサイズを可変にする 

Drivers/Super/driver_super.c, Drivers/Super/driver_super.h
Driver Super での rx frame 取得関数でいかなる場合でも NULL が返らないようにする
- https://github.com/ut-issl/c2a-core/issues/154
see diff
既存のテストがすべて通った
とくになし（NULL でフレーム確定判定されていることはない，はず）
=> Driver Super での rx frame 取得関数でいかなる場合でも NULL が返らないようにする

IfWrapper/i2c.h
I2C の ヘッダを C89 に対応
NA
CI が通れば良し
=> I2C の ヘッダを C89 に対応

Docs/General/release.md, c2a_core_main.h
Pre Release (v3.8.0-beta.2): Core の機能更新の累積に伴う update (Driver Super, I2C)
なお，**今回の PR に合わせて Release ルールを更新している**．
この更新で，Pre Release の条件が
- Tool 類の非互換が生じた時のみ
だったものを，
- Tool 類の非互換が生じた
- Bug fix や 大きな機能更新などで，本 Release 前に User サイドで最新の Core が必要になった（User 側の core update をしやすいように）
の or 条件に変更している．
以下の update などで， user サイドでの早急な取り込みが必要になったことによる pre release
- https://github.com/ut-issl/c2a-core/pull/469
- https://github.com/ut-issl/c2a-core/pull/453
すべてのテストが通った
とくになし
=> Pre Release (v3.8.0-beta.2): Release ルールの更新と Core の機能更新の累積に伴う update (Driver Super, I2C)

Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c, Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c
GENERATE TLM での他 OBC からのテレメかどうか判定するための APID 判定ロジックの改善
NA
- そもそも 2nd obc ではバグっていた
- MOBC 側でも，もっと良いロジックにした
テストが全て通った
=> GENERATE TLM での他 OBC からのテレメかどうか判定するための APID 判定ロジックの改善

Library/CMakeLists.txt, Library/libc/bsearch.c, Library/libc/memchr.c, c2a_core_main.h
- Library に `libc` ディレクトリを追加し，`bsearch()`, `memchr` を提供する
- これらの関数を使うための CMake option `USE_SIMPLE_LIBC` を追加する（デフォルトOFF）
- 関連する issue
C2A が依存するいくつかの libc 関数を自前実装し，c2a-core から提供することで，C2A の移植性を高める．
これにより，ベアメタル環境でも C2A を libc 無しに（newlib などを持ち出してくることなく）ビルド・動作させることができる．
本 core を使いたい user があるため，pre release を打つ
=> Pre Release (v3.8.0-beta.3): Add simple bsearch, memchr implementation

Docs/Core/communication.md
typo "Tlemetry" を "Telemetry" に修正
ドキュメンテーションのみの変更。
=> Fix typo "Tlemetry"

.github/workflows/python_check_format.yml, .github/workflows/python_lint.yml
CI で使っている Python のツールのバージョンを固定する
- #491 
- #492 
本当は雑に `pip install` するのではなく`Pipfile`などに書いて全環境でちゃんと固定 & Renovate で更新したいが，一旦バージョン固定されていないことにより default branch の CI が壊れるのはおかしいのでその修正
=> Use fixed version python tools

.github/workflows/python_check_format.yml, Examples/2nd_obc_user/src/src_user/Test/test/conftest.py, Examples/minimum_user/src/src_user/Test/test/conftest.py, Examples/minimum_user/src/src_user/Test/test/src_core/Applications/test_timeline_command_dispatcher.py, Examples/minimum_user/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py, Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_block_command_loader.py
Update black to 23.1.0 from 22.12.0.
- https://github.com/ut-issl/c2a-core/issues/491
=> Update black to 23.1.0 from 22.12.0

Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c, Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c
テレメ生成時のAPID判定のバグ修正
- 2nd obc からのテレメかどうかの判定がバグっていた
なぜかテレメが降りてこなくなってた
- テレメが降りてくるようになった
- pytestをすべてpass
- https://github.com/ut-issl/c2a-core/pull/492 を先にマージする
=> テレメ生成時のAPID判定のバグ修正

.gitignore, Examples/2nd_obc_user/src/src_user/Test/authorization.json.temp, Examples/2nd_obc_user/src/src_user/Test/utils/wings_utils.py, Examples/2nd_obc_user/sync_with_minimum_user.bat, Examples/minimum_user/src/src_user/Test/README.md, Examples/minimum_user/src/src_user/Test/authorization.json.temp, Examples/minimum_user/src/src_user/Test/utils/wings_utils.py, c2a_core_main.h
Pre Release (v3.8.0-beta.4): 認証なしの最新の WINGS への対応
- https://github.com/ut-issl/python-wings-interface/issues/28
- pytest でつかう WINGS の認証を削除
- すべての test が通った
- 認証ありの古い WINGS は使えなくなる
- https://github.com/ut-issl/python-wings-interface/pull/31 とともにマージする
=> Pre Release (v3.8.0-beta.4): 認証なしの最新の WINGS への対応

CMakeLists.txt, Examples/2nd_obc_user/src/src_user/IfWrapper/CMakeLists.txt, Examples/2nd_obc_user/src/src_user/IfWrapper/Sils/i2c_sils.cpp, Examples/2nd_obc_user/src/src_user/IfWrapper/SilsMockup/i2c_sils.c, Examples/minimum_user/src/src_user/IfWrapper/CMakeLists.txt, Examples/minimum_user/src/src_user/IfWrapper/Sils/i2c_sils.cpp, Examples/minimum_user/src/src_user/IfWrapper/SilsMockup/i2c_sils.c, IfWrapper/Common/i2c_common.c, IfWrapper/Common/i2c_common.h, IfWrapper/i2c.h
IfWrapper/Common配下にI2Cでデバイスのコマンドを指定してレジスタをread/writeする関数を追加する
レジスタのサイズは1バイトと2バイトに対応
I2Cでレジスタをread/writeしているc2a_userの処理を本PRで追加した関数に置き換えて
置き換え前と同じ動作をすることを確認
－
－
－
=> I2Cのread/write関数追加

Drivers/Super/driver_super.c
DS buffer のバグ修正（可変フレーム，フレーム長なし，フッタあり）
NA
以下の場合に発生するバグを修正
- 可変フレーム，フレーム長なし，フッタあり
- `DS_analyze_rx_buffer_variable_pickup_with_footer_` で解析する場合
- フレーム受信時に，そのヘッダより前にゴミデータとしてフッタの終端文字が含まれる場合
このとき，ゴミデータの終端文字をフッタと誤認してしまう．
CIとテストがすべて通る
=> DS buffer のバグ修正（可変フレーム，フレーム長なし，フッタあり）

Drivers/Super/driver_super.c, Drivers/Super/driver_super.h, Examples/2nd_obc_user/src/src_user/Applications/DriverInstances/di_mobc.c, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.h, Examples/2nd_obc_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h, Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.c, Examples/minimum_user/src/src_user/Applications/DriverInstances/di_gs.c, Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.c, Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.h, Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c, Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.h, Examples/minimum_user/src/src_user/Drivers/Com/gs.c, Examples/minimum_user/src/src_user/Drivers/Com/gs.h, Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c, Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.h, Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h
DS での rx_buffer を stream ごとに driver instance から設定可能にする
- https://github.com/ut-issl/c2a-core/issues/443
- https://github.com/ut-issl/c2a-core/issues/154
- https://github.com/ut-issl/c2a-core/issues/468
Driverが持っていた DS の rx buffer を DI で生成し，Driver に渡すようにした．
これによって，同一 Driver で複数の DI を持つコンポに対応
既存のテストがすべて通る
DI，Driverの初期化がすべて変わる
- https://github.com/ut-issl/c2a-core/pull/504 を先にマージする
=> DS での rx_buffer を stream ごとに driver instance から設定可能にする

Drivers/Super/driver_super.c, Drivers/Super/driver_super.h
DS_IF_RX_BUFFER_SIZE の可変長化
- https://github.com/ut-issl/c2a-core/issues/464
issueとdiffで追加した DS のコメントを参照
既存のテストがすべて通った
rx_bufferサイズのバリデーションがより厳しくなっていることに注意
- https://github.com/ut-issl/c2a-core/pull/505 をマージしてからマージすること
=> DS_IF_RX_BUFFER_SIZE の可変長化

Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.c, Drivers/Super/driver_super.c, Drivers/Super/driver_super.h, c2a_core_main.h
Pre Release (v3.8.0-beta.5): DS に受信フレームの最大値の設定を追加
- https://github.com/ut-issl/c2a-core/issues/496
- https://github.com/ut-issl/c2a-core/issues/468
issue と driver_super.h で diff にでるコメントを参照
CIとすべてのテストが通った
- https://github.com/ut-issl/c2a-core/pull/507 を先にマージする
- これで Driver Super, DS の大きな改修が一段落するので，Pre Release を打つ
=> Pre Release (v3.8.0-beta.5): DS に受信フレームの最大値の設定を追加

CMakeLists.txt, Library/CMakeLists.txt
CMake のオプション定義が深い階層にあると適切に動作しない場合があるので，top の `CMakeLists.txt` に移す
=> Fix USE_SIMPLE_LIBC option definition to top

Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py, TlmCmd/command_dispatcher.c, TlmCmd/command_dispatcher.h
CDISの実行エラーのEL登録のlocal id を cmd id にした
- https://github.com/ut-issl/c2a-core/issues/480
issueの通り。cmd id ごとに EL 登録を無効化したいというのが最大のモチベ。
手元で修正したpytestを通した
=> CDISの実行エラーのEL登録のlocal id を cmd id にした

Applications/timeline_command_dispatcher.c
BC展開時刻被りはコマンド実行エラーにしないようにした
- https://github.com/ut-issl/c2a-core/issues/483
詳しくは issue
pytest を手元で回して全て通った
=> BC展開時刻被りはコマンド実行エラーにしないようにした

.github/workflows/build_with_s2e.yml
S2E Build CI で使われる S2E Core のバージョンを上げる
- 関連する issue
- https://github.com/ut-issl/c2a-core/pull/533 で CI がこけたので，なおす．
- https://github.com/ut-issl/s2e-user-for-c2a-core/pull/27 によって，使われる S2E core が v6.0.0 に
CI が通ればOK
=> S2E Build CI で使われる S2E Core のバージョンを上げる

Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c, Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.h, Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c, Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.h, TlmCmd/telemetry_generator.c
APID_is_other_obc_tlm_apid の削除
- https://github.com/ut-issl/c2a-core/issues/489
メンテ性が最悪なこの関数を削除
この後，満を持して，generate tlmの改修にはいる
MOBCとAOBC (2nd OBC) で，きちんと CTP の primary header が区別されていることを手元で確認した
APID_is_other_obc_tlm_apid をすべて削除することができる
=> APID_is_other_obc_tlm_apid の削除

Examples/2nd_obc_user/src/src_user/IfWrapper/CMakeLists.txt, Examples/minimum_user/src/src_user/IfWrapper/CMakeLists.txt
- 分かりにくい if 文を修正
- `list(APPEND)` を使わないようにした
- 関連する issue
詳しく
XX系の動作がガラッと変わる，とか．
何かあれば
- 関連する Projects が存在する場合，それの紐付けを行うこと
- Assignees を設定すること
- 可能ならば Reviewers を設定すること
- 可能ならば `priority` ラベルを付けること
=> Refactor example user IfWrapper CMake

CMakeLists.txt, c2a_core_main.h, common.cmake
Pre Release (v3.9.0-beta.2): Split C89 compile option to BUILD_C2A_AS_C99
C99 のためのコンパイルオプションの指定を `BUILD_C2A_AS_C99` に分割する
- #102 
- Resolve #526
- C99 のためのコンパイルオプションを隔離し，`BUILD_C2A_AS_C99` という CMake オプションに分割
- `BUILD_C2A_AS_C99` は c2a-core では default OFF とする（C89 な C2A user が存在するため）
- `BUILD_C2A_AS_C99 = ON` のとき，C99 としてビルドする
- C89 である必要の無い C2A user では必ずこれを設定するようにし，C99 に寄せていく
C99 でビルドしており，かつ，#526 のような雑な `common.cmake` を書いていた C2A user のみ `BUILD_C2A_AS_C99=ON` にする対応が必要（ただし，これをしていた場合 clang で意図した挙動になっていないため，このパッチを取り込む必要がある）
=> Pre Release (v3.9.0-beta.2): Split C89 compile option to BUILD_C2A_AS_C99

.gitignore, Cargo.toml, Docs/General/release.md, c2a_core_main.h
c2a-core を Rust の crate としてパッケージングする
c2a-core は現状あくまでC言語で書かれており，Rustのプロジェクト **ではない** が，Cargo などのエコシステムだけでも Rust のものに載せる価値は十分にある．
その前準備として，`Cargo.toml` だけを追加し，crate として公開する．
リリースの手順が変わる．具体的には，バージョン番号を`Cargo.toml` でも管理するようにする．
- この PR のマージ後，Pre Release でよいのでリリースを打ってほしい（`Cargo.toml` も更新する必要があるので注意）
=> Pre Release (v3.9.0-beta.3): Packaging as Rust crate

TlmCmd/packet_list.c
packet list の変数名が pli と pl で表記ゆれしていたのを pl に統一する
CI がとおればOK
=> packet list の変数名が pli と pl で表記ゆれしていたのを pl に統一する

Cargo.toml
crate の metadata が `non-standard` となってしまっているので，明示的に `license = "MIT"` も追加する
- #564
=> Fix crate package license config

Cargo.toml, src/lib.rs
- `c2a-core` crate に `export-src` feature を追加
- `export-src` feature のときのみ，この crate のソースコードがあるディレクトリを露出させるためのユーティリティ関数を追加
- #564 
- #567 
- `c2a-core` crate のみ
- `export-src` feature の時は `no_std` ではなくなる
マージ後リリースしてほしい
=> Add export src interface (c2a-core crate)

Docs/Core/communication.md, Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c, Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.c, Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h, Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.c, Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.c, Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.c, Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h, Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.c, TlmCmd/common_cmd_packet.h, TlmCmd/packet_handler.c, c2a_core_main.h
CCP_DEST_TYPE_TO_APID を追加し，コマンドのルーティングを見直す
- https://github.com/ut-issl/c2a-core/issues/512
`CCP_DEST_TYPE_TO_APID` を追加し，APID の最終到達地点がキューイングの宛先の場合，個別に DEST_TYPE を設定することが不要になった
既存のテストが全て通った
- `PH_user_analyze_cmd` の書き換えが必要
- MOBC にある 2nd OBC の driver の微修正が必要
=> Pre Release (v3.9.0-beta.4): CCP_DEST_TYPE_TO_APID を追加し，コマンドのルーティングを見直す

Cargo.toml
Pre Release (v3.9.0-beta.4): バージョンアップのやり直し
- https://github.com/ut-issl/c2a-core/pull/561 で Cargo.toml のバージョンを上げそびれた
=> Pre Release (v3.9.0-beta.4): バージョンアップのやり直し

Cargo.toml, Examples/2nd_obc_user/src/src_user/TlmCmd/command_definitions.c, Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c, Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c, Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c, c2a_core_main.h
Pre Release (v3.9.0-beta.5): tlm-cmd-code-generator の更新
NA
tlm-cmd-code-generator 側を更新し，include を改善
以下とともにマージする
- https://github.com/ut-issl/c2a-tlm-cmd-code-generator/pull/37
CI が通れば OK
=> Pre Release (v3.9.0-beta.5): tlm-cmd-code-generator の更新

Cargo.toml
crate の `package.license` と `package.license-file` は冗長で warning が出るので，`package.license` だけにする
=> Remove duplicate Rust crate package license config

Cargo.toml, build.rs
`c2a_core_main.h` で定義されるバージョン情報を Rust の build script から読んで検証する
- #570 
- `clang-rs` を用いて `c2a_core_main.h` をパースし，`C2A_CORE_VER_MAJOR` 等を Rust から読み込む
- define macro はあくまで preprocess で AST には直接出てこないので，多少自前でパースしてやる必要はある
- crate の `package.version` と一致しているか検証（`assert_eq()`）
- 不一致の場合，`cargo build` がコケる
CI は Rust のビルド CI として別途追加する
=> Check c2a-core version header in Rust build script

.github/workflows/rust.yml, c2a_core_main.h
Rust の CI workflow を追加
- Resolve #570 
- `c2a-core` crate 向けの普通の Rust の CI を追加
- #573 により，バージョンの不整合があるとビルドがコケるのでこの CI で検知できる
=> Add rust ci

System/TaskManager/task_dispatcher.c, System/TimeManager/obc_time.c, System/TimeManager/obc_time.h, System/TimeManager/obc_time_config.h, System/TimeManager/time_manager.c
`ObcTime` の設定を `obc_time.h` から分割する
- #581 
- `obc_time.h` が C2A user に依存しなくなる
- `ObcTime` のデフォルト設定は `obc_time_config.h` で定義するようになる
CI が通ればよし
=> Split obc time config header

Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/sample.ops, Examples/2nd_obc_user/src/src_user/Test/test/conftest.py, Examples/2nd_obc_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c, Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c, Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/sample.ops, Examples/minimum_user/src/src_user/Test/test/conftest.py, Examples/minimum_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c
古い `GENERATE_TLM` の利用を消す（telemetry manager , pytest 以外）
- https://github.com/ut-issl/c2a-core/issues/543
- サンプルコマンドファイルの修正
- その他あったものを削除
既存のテストが全て通ればOK
- pytest は https://github.com/ut-issl/c2a-core/pull/588 で
- tlm mgr については https://github.com/ut-issl/c2a-core/issues/556 で
=> 古い `GENERATE_TLM` の利用を消す（telemetry manager , pytest 以外）

.github/workflows/rust.yml, Cargo.toml
`clang` crate（正確にはその dependency の `clang-sys` crate）の `runtime` feature を使って libclang をリンクする
- `clang-runtime` feature を追加
- ここで `clang` crate に  `runtime` feature を指定
- `clang-runtime` を default feature にした
CI や `c2a-core` crate のユーザが `libclang` のリンクのことを考えなくてよくなる
一連のPRマージ後にPre Release したい
=> Add clang runtime feature

Cargo.toml, build.rs
Cargo を経由して `c2a-core` crate のソースファイルのディレクトリを依存先の crate に公開する
- #568 
- https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key
- `c2a-core` crate のユーザー
リリースしたい
=> Export src dir via cargo

.github/workflows/check_coding_rule.yml
- Resolve #517 
- CI が通ったらよし
- https://github.com/ut-issl/c2a-core/actions/runs/5006365128/jobs/8971548564?pr=578
=> Remove set-output

Cargo.toml, Examples/2nd_obc_user/src/src_user/Test/test/test_comm_between_c2a.py, Examples/minimum_user/src/src_user/Test/test/src_core/Applications/test_event_utility.py, Examples/minimum_user/src/src_user/Test/test/src_core/Applications/test_timeline_command_dispatcher.py, Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py, Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py, Examples/minimum_user/src/src_user/Test/test/src_core/System/ModeManager/test_mode_manager.py, Examples/minimum_user/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py, Examples/minimum_user/src/src_user/Test/test/src_core/System/WatchdogTimer/test_watchdog_timer.py, Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_block_command_loader.py, Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_analyze.py, Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py, Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_common_cmd_packet_util.py, Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_telemetry_frame.py, c2a_core_main.h
Pre Release (v3.9.0-beta.7): pytest 内の古い `GENERATE_TLM` の利用を消す
- https://github.com/ut-issl/c2a-core/issues/543
- https://github.com/ut-issl/c2a-core/pull/584 のつづき
- https://github.com/ut-issl/c2a-core/issues/542
ツール側の修正もあるので，以下とともにマージする
- https://github.com/ut-issl/python-wings-interface/pull/34
- 既存の pytest が全て通った
test の tlm 生成の書き方が全部変わる（過去のものは実行時エラーになる）
=> Pre Release (v3.9.0-beta.7): pytest 内の古い `GENERATE_TLM` の利用を消す

Cargo.toml, c2a_core_main.h
Update version (v3.9.0)
- https://github.com/ut-issl/c2a-core/issues/514
v3.9.0 リリース前の，バージョン上げ
=> Update version (v3.9.0)

common.cmake
不要な `-rdynamic` リンクオプションを削除
- `-rdynamic` は実行ファイルないし共用ライブラリにのみ効果のあるリンクオプション
- そのため，単体ではビルドできない c2a-core で指定しても意味が無い
- `PUBLIC` 指定されているので `add_subdirectory()` 先にも波及するが，c2a-core の責務を逸脱している
- このオプションの主な用途である SILS-S2E の場合は S2E 側でそもそも指定されているため，このオプションが必要なケースでもここには不要（ref: https://github.com/ut-issl/s2e-core/blob/3a2f3fcc290848e6246cab2b1284645f8ff62f2a/common.cmake#L24-L25）
- 一方で，`-rdynamic` をサポートしないようなターゲットでは，このオプションがこのような形で存在することによってビルドに失敗するケースがある
CI が通ればよし
- CMake でのビルド環境
- リリースしたい
- まだ breaking なものが 3.9.0 以降マージされていないため，3.9.1 としたい
=> Remove unused -rdynamic link option

TlmCmd/common_cmd_packet_util.c
主に c2a-user 側でビルドする際に問題となる:
- C としてビルドする場合: `-Werror` オプションでも（何故か）引っかからないが，潜在的には NG
- C++ としてビルドする場合: そもそもビルドに通らない．
なし．
コミットログを参照．
common_command_packet 周り．
類似の問題を網羅的に解決する訳ではないが，今後似たようなエラーに遭遇したら都度対処予定です．
=> 異なる型の enum を比較している箇所を修正する

Library/endian.c
endian.c の include の修正
NA
memcpy をつかってるのに string.h が include されてないのはおかしい
あるマイコンでエラーが出た
CIがとおればよし
=> endian.c の include の修正

common.cmake
SSIA
MSVC でのビルドで大量に出ている `#pragma SECTION` 起因の warning を無効化する
=> Ignore pragma section REPRO warning on MSVC

Applications/event_utility.c, Applications/nop.c
プロトタイプ宣言と定義の表記揺れ（というか `void` の有無）を修正
see diff
warning が減る
マージ後 3.9.2 をリリースしたい
=> Fix function prototype mismatch in Applications

Cargo.toml, c2a_core_main.h
Update version (v3.10.1)
N/A
v3.10.1 リリース前の，バージョン上げ
=> Update version (v3.10.1)
